---
title: "Curriculum vitae"
format: html
---

*A PDF copy of my complete CV is available upon [request](index.qmd#contact).*

# Employment

03/2024–present: Postdoctoral researcher, Linguistics and English Language, University of Edinburgh.

10/2022–05/2023: Fixed Term Teacher, Department of Language and Linguistics, University of Essex.

11/2021–09/2022: Research Fellow, Department of Language and Linguistics, University of Essex.

10/2021–09/2022: Departmental Lecturer in Phonetics and Phonology, Faculty of Linguistics, Philology and Phonetics, University of Oxford.

# Education

09/2016–05/2021: PhD in Linguistics, University of Manchester.

09/2014–09/2015: MA in Linguistics, University of Manchester, distinction.

10/2010–07/2014: BA (Hons) in French and Russian, University of Bristol, 2:1.

# Research assistantships

06/2021: Intonational plateaux in Belfast, Cambridge, Liverpool and Newcastle English, Hae-Sung Jeon, University of Central Lancashire.

09/2015–09/2016: The Meaning of Verbal Roots Across Languages, Andrew Koontz-Garboden, University of Manchester and John Beavers, University of Texas at Austin.

11/2015–02/2016: Segmentation and transcription of Ngarinyman fieldwork recordings, Eva Schultze-Berndt, University of Manchester.

# Laboratory assistantships

09/2017–08/2019: University of Manchester Phonetics Lab assistant (with Stefano Coretta 2017–18 and Kǎiyuè Xíng 2018–19).

# Teaching assistantships

Autumn 2019: *Language, Mind and Brain*, 1Y UG, University of Manchester. Marking only. Course leader: Wendell Kimper.

Spring 2019: *Phonology*, 2Y UG, University of Manchester. Course leader: Ricardo Bermúdez-Otero.

Autumn 2018: *Quantitative Methods in Language Sciences*, 2Y UG, University of Manchester. Course leader: Patrycja Strycharczuk.

Spring 2018: *The Sounds of Language*, 1Y UG, University of Manchester. Course leader: Patrycja Strycharczuk.

Autumn 2017: *Typology*, 2Y UG, University of Manchester. Course leader: Eva Schultze-Berndt.

Spring 2013: English-language teaching assistant, Tyumen State Oil and Gas University.

# Other teaching

12/12/2019: Phonetics and Phonology exam revision session for MA in Linguistics students, University of Manchester. Course leader: Ricardo Bermúdez-Otero.

22/01/2019. Teaching assistant, *An Introduction to Using R for Data Analysis*, 6.5-hour Digital Humanities course, University of Manchester. Trainer: David Mawdsley.

# Outreach

23/01/2020: Ultrasound tongue imaging in studying English dialects (with Kǎiyuè Xíng), 1 x 40-minute taster session at *Discover English, Drama & American Studies Day* for Y12 students, University of Manchester.

02/07/2019: Ultrasound tongue imaging in studying English dialects (with Kǎiyuè Xíng), 2 x 40-minute taster session at *Discover English, Drama & American Studies Day* for Y12 students, University of Manchester.

27/06/2019: Ultrasound tongue imaging in studying English dialects (with Kǎiyuè Xíng), 2 x 45-minute taster session at *Insight into Linguistics and English Language* for Y12 students, University of Manchester.

# Conference organisation

2019: Organising committee member, 2019 Symposium on Representations, Usage and Social Embedding in Language Change.

2017–2019: Deputy lead organiser, 2018 and 2019 Manchester Fora in Linguistics.

2016–2017: Lead organiser, 2017 Manchester Forum in Linguistics.

2016–2017: Organisatory helper, 24^th^ and 25^th^ Manchester Phonology Meetings.

# Awards

2024: JIPA Most Illustrative Illustration Prize [\[Northern Tosk Albanian\]](https://doi.org/10.1017/S0025100322000044)

03/2019: Philological Society Early Career Researcher travel bursary.

04/2018: Eugénie Henderson Prize for the best poster presentation at the Colloquium of the British Association of Academic Phoneticians.

2016–2019: Postgraduate Research Studentship, School of Arts, Languages and Cultures, Faculty of Humanities, University of Manchester.
