---
title: "Talks and posters"
format: html
---

*If you are unable to access any of my work from this page and would like a copy, feel free to [contact](index.qmd#contact) me.*

# Invited talks

[Nichols, Stephen]{.underline}. 2023. Vowel harmony in Bantu: On phonology, typology and grounding. Invited plenary talk given at the Manchester Forum in Linguistics, Manchester, UK, 20--21 April. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2023-mfil-bantu.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2022. Variation, change and phonetic grounding: The case of the mid front vowels of Turkish. Invited talk given at the University of Oxford General Linguistics Seminar, Oxford, UK, 2 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-gls-turkish.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline} & George Bailey. 2019. \[ʃ\]tranger things have happened: Retraction in (str) and (stj) clusters in Manchester English. Invited talk given at the Glasgow University Laboratory of Phonetics Lab Lunch, Glasgow, UK, 6 June. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-gulp-str.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline} & George Bailey. 2018. All paths lead to \[ʃ\]: Varying sibilant articulation and *s*-retraction in Manchester English. Invited talk given at the University of Manchester Linguistics and English Language Research Seminar, Manchester, UK, 9 October. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-uom-str.pdf){target="_blank" title="Download slides"}

# Conference talks

[Nichols, Stephen]{.underline}. 2023. Investigating vowel harmony in Ihanzu. Talk given virtually at the Ihanzu Symposium, Bielefeld, Germany, 29 September. DOI: [10.5281/zenodo.8393386](https://doi.org/10.5281/zenodo.8393386){target="_blank"}. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2023-ihanzu-vh.pdf){target="_blank" title="Download slides"} [<i class="fa-brands fa-youtube" style="color: $link-color;"></i>](https://youtu.be/6r82XQraxVE){target="_blank" title="Watch on YouTube"}

Bailey, George & [Stephen Nichols]{.underline}. 2023. An articulatory study of /s/-retraction: How does thish change behave across word boundaries? Talk given at UK Language Variation and Change 14, Edinburgh, UK, 26--28 June. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2023-uklvc-str.pdf){target="_blank" title="Download slides"}

Bailey, George & [Stephen Nichols]{.underline}. 2022. Post-lexical /s, z/-retraction in Manchester English: An ultrasound-tongue-imaging and lip-camera study. Talk given at Ultrafest X, Manchester, UK, 3--4 November. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-ultrafest-str.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline} & George Bailey. 2022. New ways of analysing sibilant palatalisation: The acoustics and articulation of post-lexical /s, z/-retraction in Manchester English. Talk given virtually at New Ways of Analyzing Variation 50, Stanford, CA, US, 13--15 October. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-nwav-str.pdf){target="_blank" title="Download slides"}

Gopal, Deepthi & [Stephen Nichols]{.underline}. 2022. Apparent-time change in Turkish front-mid-vowel allophony. Talk given at the Annual Meeting of the Linguistics Association of Great Britain, Belfast, UK, 13--15 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-lagb-turkish.pdf){target="_blank" title="Download slides"}

Dobui, Bien, Yuni Kim, Jair Apóstol Polanco, Natalia Hernández & [Stephen Nichols]{.underline}. 2022. A three-way prosodic contrast in Amuzgo word-initial NC sequences? Talk given at the Annual Meeting of the Linguistics Association of Great Britain, Belfast, UK, 13--15 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-lagb-amuzgo.pdf){target="_blank" title="Download slides"}

Kim, Yuni, Bien Dobui, [Stephen Nichols]{.underline}, Natalia Hernández & Jair Apóstol Polanco. 2022. A novel three-way prosodic contrast in Amuzgo word-initial NC sequences. Talk given at the Phonology of Nasals, Nasality and Nasalization across Languages workshop at the 19^th^ Meeting of the French Phonology Network, Porto, Portugal, 7--9 June. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-rfp-amuzgo.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}, Enkeleida Kapia, Josiane Riverin-Coutlée & Stefano Coretta. 2021. Towards a description of the rhotic sounds of Northern Tosk Albanian. Talk given virtually at the 7^th^ International Workshop on Phonetic, Phonological, Acquisitional, Sociolinguistic and Dialect-Geographic Aspects of Rhotics, Lausanne, Switzerland, 18--19 November. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2021-ratics-shqr.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}, Josiane Riverin-Coutlée & Stefano Coretta & Enkeleida Kapia. 2021. On the acoustics and articulation of the affricates of Northern Tosk Albanian. Talk given virtually at the Annual Meeting of the Linguistics Association of Great Britain, 6--9 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2021-lagb-shqaffricates.pdf){target="_blank" title="Download slides"}

Bailey, George, [Stephen Nichols]{.underline}, Maciej Baranowski & Danielle Turton. 2019. Affrication as the cause of *s*-retraction: Community-level change in Manchester English. Talk given at New Ways of Analyzing Variation 48, Eugene, OR, US, 10--12 October. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-nwav-str.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline} & Henri Kauhanen. 2019. Vowel-pair rank--frequency distributions are polylogarithmic. Talk given at the Annual Meeting of the Linguistics Association of Great Britain, London, UK, 9--12 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-lagb-vowelpairs.pdf){target="_blank" title="Download slides"}

Bailey, George, [Stephen Nichols]{.underline}, Maciej Baranowski & Danielle Turton. 2019. A \[ʃ\]triking change in Manchester English. Talk given at UK Language Variation and Change 12, London, UK, 3--5 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-uklvc-str.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2019. Asymmetries in vowel-pair frequencies and height harmony in Bantu. Talk given at the 50^th^ Annual Conference on African Linguistics, Vancouver, BC, Canada, 23--25 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-acal-freq.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2019. A study of vowel-pair frequencies in Lozi: Implications for formal analyses. Talk given at the Manchester Forum in Linguistics, Manchester, UK, 2--3 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-mfil-lozi.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2019. Vowel-pair frequencies and phonotactic restrictions in Lozi. Talk given at the Philological Society Early Career Researcher Forum, Oxford, UK, 8--9 March. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-philsoc-lozi.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline} & George Bailey. 2018. Revealing covert articulation in *s*-retraction. Talk given at the Annual Meeting of the Linguistics Association of Great Britain, Sheffield, UK, 11--14 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-lagb-str.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2018. A workflow and methodology for investigating vowel-to-vowel coarticulation. Talk given at the 13^th^ Annual Language at the University of Essex Conference, Colchester, UK, 14 June. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-langue-workflow.pdf){target="_blank" title="Download slides"}

Bailey, George & [Stephen Nichols]{.underline}. 2018. Retraction on Coronation \[ʃ\]treet: An ultrasound-tongue-imaging study of *s*-retraction in Manchester English. Talk given at the 8^th^ Northern Englishes Workshop, Newcastle upon Tyne, UK, 27--28 March. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-new-str.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2018. Accounting for height harmony in five-vowel Bantu languages: Positional faithfulness and feature co-occurrence constraints. Talk given at the 49^th^ Annual Conference on African Linguistics, East Lansing, MI, US, 22--25 March. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-acal-bantu.pdf){target="_blank" title="Download slides"}

[Nichols, Stephen]{.underline}. 2018. Positional faithfulness and feature co-occurrence constraints in the height harmony systems of five-vowel Bantu languages. Talk given at the 15^th^ Old World Conference in Phonology, London, UK, 12--14 January. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-ocp-bantu.pdf){target="_blank" title="Download handout"}

[Nichols, Stephen]{.underline}. 2017. Nasal harmony in Kamaiurá: Syllabification and spreading. Talk given at the Annual Meeting of the Linguistics Association of Great Britain, Canterbury, UK, 4--7 September. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2017-lagb-kamaiura.pdf){target="_blank" title="Download handout"}

Gopal, Deepthi & [Stephen Nichols]{.underline}. 2017. Sonorant-conditioned mid vowel lowering in Turkish. Talk given at the 14^th^ Old World Conference in Phonology, Düsseldorf, Germany, 20--22 February. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2017-ocp-turkish.pdf){target="_blank" title="Download handout"}

Beavers, John, Michael Everdell, Kyle Jerro, Henri Kauhanen, Andrew Koontz-Garboden, Elise LeBovidge & [Stephen Nichols]{.underline}. 2017. Two Types of States: A Cross-Linguistic Study of Change-of-State Verb Roots. Talk given at the 91^st^ Annual Meeting of the Linguistics Society of America, Austin, TX, US, 5--8 January. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2017-lsa-cos.pdf){target="_blank" title="Download handout"}

[Nichols, Stephen]{.underline}. 2016. The representation of nasality in Konai. Talk given at the CLUL Linguistics Meeting for Young Researchers, Lisbon, Portugal, 16 June. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2016-clul-konai.pdf){target="_blank" title="Download handout"}

Gopal, Deepthi & [Stephen Nichols]{.underline}. 2016. Sonorant-conditioned mid vowel lowering in Turkish. Talk given at the 24th Manchester Phonology Meeting, Manchester, UK, 26--28 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2016-mfm-turkish.pdf){target="_blank" title="Download handout"}

# Conference posters

[Nichols, Stephen]{.underline}. 2024. Towards a phonetically-informed description of vowel harmony in Ihanzu. Poster presented at the Réseau Français de Phonologie, Amiens, France, 26--28 June. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2024-rfp-ihanzu.pdf){target="_blank" title="Download poster"}

[Nichols, Stephen]{.underline}. 2024. Towards a phonetically-informed description of vowel harmony in Ihanzu. Poster presented at the Colloquium of the British Association of Academic Phoneticians, Cardiff, UK, 25--27 March. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2024-baap-ihanzu.pdf){target="_blank" title="Download poster"}

Gopal, Deepthi & [Stephen Nichols]{.underline}. 2022. Variation, gradience and categoricity in the Turkish mid vowels. Poster presented virtually at the Colloquium of the British Association of Academic Phoneticians, York, 4--8 April. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-baap-turkish.pdf){target="_blank" title="Download poster"}

[Nichols, Stephen]{.underline}. 2019. Vowel-pair frequencies and phonotactic restrictions in Lozi. Poster presented at Fonologi i Norden, Edinburgh, UK, 22--23 February. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2019-fino-lozi.pdf){target="_blank" title="Download poster"}

Bailey, George & [Stephen Nichols]{.underline}. 2018. Patterns of *s*-retraction in Manchester English: Investigating categoricity with ultrasound. Poster presented at the 26^th^ Manchester Phonology Meeting, Manchester, UK, 24--26 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-mfm-str.pdf){target="_blank" title="Download poster"} [<i class="fa-solid fa-bars" style="color: $link-color;"></i>](files/2018-mfm-str-ref.pdf){target="_blank" title="Download references"}

[Nichols, Stephen]{.underline} & George Bailey. 2018. Gradience and categoricity in *s*-retraction: An ultrasound study of Manchester English. Poster presented at the Colloquium of the British Association of Academic Phoneticians, Canterbury, UK, 12--14 April. [\[Winner of the 2019 Eugénie Henderson Prize\]](https://blogs.kent.ac.uk/baap/){target="_blank"} [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2018-baap-str.pdf){target="_blank" title="Download poster"} [<i class="fa-solid fa-bars" style="color: $link-color;"></i>](files/2018-baap-str-ref.pdf){target="_blank" title="Download references"} [<i class="fa-solid fa-paperclip" style="color: $link-color;"></i>](files/2018-baap-str-app.pdf){target="_blank" title="Download appendix"}

[Nichols, Stephen]{.underline}. 2017. Nasal spreading and syllabification in Kamaiurá. Poster presented at the 25^th^ Manchester Phonology Meeting, Manchester, UK, 25--27 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2017-mfm-kamaiura.pdf){target="_blank" title="Download poster"}

Gopal, Deepthi, Henri Kauhanen & [Stephen Nichols]{.underline}. 2017. Modelling similarity-driven phonological generalisations. Poster presented at the 4^th^ International Workshop on Sound Change, Edinburgh, UK, 20--22 April. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2017-wsc-similarity.pdf){target="_blank" title="Download poster"}

[Nichols, Stephen]{.underline}. 2016. Nasal cluster dissimilation in Ngarinyman. Poster presented at the 24^th^ Manchester Phonology Meeting, Manchester, UK, 26--28 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2016-mfm-ncd.pdf){target="_blank" title="Download poster"}

[Nichols, Stephen]{.underline}. 2016. An acoustic study of the Turkish rhotic. Poster presented at the 5^th^ International Workshop on Phonetic, Phonological, Acquisitional, Sociolinguistic and Dialect-Geographic Aspects of Rhotics, Leeuwarden, Netherlands, 18--20 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2016-ratics-turkish.pdf){target="_blank" title="Download poster"}

# Other talks

[Nichols, Stephen]{.underline}. 2022. Making the most of existing tools for the forced-alignment and segmentation of under-resourced languages. Talk given at the University of Oxford's Lab Skills Workshop series, Oxford, UK, 4 March. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2022-labskills-sppas.pdf){target="_blank" title="Download slides"}

Kapia, Enkeleida, Josiane Riverin-Coutlée, [Stephen Nichols]{.underline} & Stefano Coretta. 2021. Expecting the unexpected: (Re)discovered variation in Albanian phonetics. Talk given virtually at the Institute of Phonetics and Speech Processing Kolloquium, Munich, Germany, 6 May. [<i class="fa-solid fa-file-pdf" style="color: $link-color;"></i>](files/2021-kolloq-shqipa.pdf){target="_blank" title="Download slides"}
